  "https://unpkg.com/sweetalert/dist/sweetalert.min.js"

  function coolPrompt() {
      var birthday = prompt("Enter your birthday , Example Apr 12 , ");
      switch (birthday) {
          case "Jan 21":
          case "Jan 22":
          case "Jan 23":
          case "Jan 24":
          case "Jan 25":
          case "Jan 26":
          case "Jan 27":
          case "Jan 28":
          case "Jan 29":
          case "Jan 30":
          case "Jan 31":
          case "Fab 1":
          case "Fab 2":
          case "Fab 3":
          case "Fab 4":
          case "Fab 5":
          case "Fab 6":
          case "Fab 7":
          case "Fab 8":
          case "Fab 9":
          case "Fab 10":
          case "Fab 11":
          case "Fab 12":
          case "Fab 13":
          case "Fab 14":
          case "Fab 15":
          case "Fab 16":
          case "Fab 17":
          case "Fab 18":
          case "Fab 19":
              swal("Your Horoscope is AQUARIUS", "info");
              break;
          case "Fab 20":
          case "Fab 21":
          case "Fab 22":
          case "Fab 23":
          case "Fab 24":
          case "Fab 25":
          case "Fab 26":
          case "Fab 27":
          case "Fab 28":
          case "Fab 29":
          case "Mar 1":
          case "Mar 2":
          case "Mar 3":
          case "Mar 4":
          case "Mar 5":
          case "Mar 6":
          case "Mar 7":
          case "Mar 8":
          case "Mar 9":
          case "Mar 10":
          case "Mar 11":
          case "Mar 12":
          case "Mar 13":
          case "Mar 14":
          case "Mar 15":
          case "Mar 16":
          case "Mar 17":
          case "Mar 18":
          case "Mar 19":
          case "Mar 20":
              swal("Your horoscope is PISCES , info");
              break;
          case "Mar 21":
          case "Mar 22":
          case "Mar 23":
          case "Mar 24":
          case "Mar 25":
          case "Mar 26":
          case "Mar 27":
          case "Mar 28":
          case "Mar 29":
          case "Mar 30":
          case "Mar 31":
          case "Apr 1":
          case "Apr 2":
          case "Apr 3":
          case "Apr 4":
          case "Apr 5":
          case "Apr 6":
          case "Apr 7":
          case "Apr 8":
          case "Apr 9":
          case "Apr 10":
          case "Apr 11":
          case "Apr 12":
          case "Apr 13":
          case "Apr 14":
          case "Apr 15":
          case "Apr 16":
          case "Apr 17":
          case "Apr 18":
          case "Apr 19":
          case "Apr 20":
              swal("Your Horoscope is ARIES , info");
              break;
          case "Apr 21":
          case "Apr 22":
          case "Apr 23":
          case "Apr 24":
          case "Apr 25":
          case "Apr 26":
          case "Apr 27":
          case "Apr 28":
          case "Apr 29":
          case "Apr 30":
          case "May 1":
          case "May 2":
          case "May 3":
          case "May 4":
          case "May 5":
          case "May 6":
          case "May 7":
          case "May 8":
          case "May 9":
          case "May 10":
          case "May 11":
          case "May 12":
          case "May 13":
          case "May 14":
          case "May 15":
          case "May 16":
          case "May 17":
          case "May 18":
          case "May 19":
          case "May 20":
          case "May 21":
              swal("your Horoscope is TAURUS , info");
              break;
          case "May 22":
          case "May 23":
          case "May 24":
          case "May 25":
          case "May 26":
          case "May 27":
          case "May 28":
          case "May 29":
          case "May 30":
          case "May 31":
          case "Jun 1":
          case "Jun 2":
          case "Jun 3":
          case "Jun 4":
          case "Jun 5":
          case "Jun 6":
          case "Jun 7":
          case "Jun 8":
          case "Jun 9":
          case "Jun 10":
          case "Jun 11":
          case "Jun 12":
          case "Jun 13":
          case "Jun 14":
          case "Jun 15":
          case "Jun 16":
          case "jun 17":
          case "jun 18":
          case "Jun 19":
          case "Jun 20":
          case "Jun 21":
              swal("Your horoscope is GEMINI , info");
              break;
          case "Jun 22":
          case "Jun 23":
          case "Jun 24":
          case "Jun 25":
          case "Jun 26":
          case "Jun 27":
          case "Jun 28":
          case "Jun 29":
          case "Jun 30":
          case "Jul 1":
          case "Jul 2":
          case "Jul 3":
          case "Jul 4":
          case "Jul 5":
          case "Jul 6":
          case "Jul 7":
          case "Jul 8":
          case "Jul 9":
          case "Jul 10":
          case "Jul 11":
          case "Jul 12":
          case "Jul 13":
          case "Jul 14":
          case "Jul 15":
          case "Jul 16":
          case "Jul 17":
          case "Jul 18":
          case "Jul 19":
          case "Jul 20":
          case "Jul 21":
          case "Jul 22":
              swal("your horoscope is CANCER , info");
              break;
          case "Jul 23":
          case "Jul 24":
          case "Jul 25":
          case "Jul 26":
          case "Jul 27":
          case "Jul 28":
          case "Jul 29":
          case "Jul 30":
          case "Jul 31":
          case "Aug 1":
          case "Aug 2":
          case "Aug 3":
          case "Aug 4":
          case "Aug 5":
          case "Aug 6":
          case "Aug 7":
          case "Aug 8":
          case "Aug 9":
          case "Aug 10":
          case "Aug 11":
          case "Aug 12":
          case "Aug 13":
          case "Aug 14":
          case "Aug 15":
          case "Aug 16":
          case "Aug 17":
          case "Aug 18":
          case "Aug 19":
          case "Aug 20":
          case "Aug 21":
          case "Aug 22":
              swal("your Horoscope is LEO , info");
              break;
          case "Aug 23":
          case "Aug 24":
          case "Aug 25":
          case "Aug 26":
          case "Aug 27":
          case "Aug 28":
          case "Aug 29":
          case "Aug 30":
          case "Aug 31":
          case "Sep 1":
          case "Sep 2":
          case "Sep 3":
          case "Sep 4":
          case "Sep 5":
          case "Sep 6":
          case "Sep 7":
          case "Sep 8":
          case "Sep 9":
          case "Sep 10":
          case "Sep 11":
          case "Sep 12":
          case "Sep 13":
          case "Sep 14":
          case "Sep 15":
          case "Sep 16":
          case "Sep 17":
          case "Sep 18":
          case "Sep 19":
          case "Sep 20":
          case "Sep 21":
          case "Sep 22":
              swal("Your Horoscope is VIRGO , info");
              break;
          case "Sep 23":
          case "Sep 24":
          case "Sep 25":
          case "Sep 26":
          case "Sep 27":
          case "Sep 28":
          case "Sep 29":
          case "Sep 30":
          case "Oct 1":
          case "Oct 2":
          case "Oct 3":
          case "Oct 4":
          case "Oct 5":
          case "Oct 6":
          case "Oct 7":
          case "Oct 8":
          case "Oct 9":
          case "Oct 10":
          case "Oct 11":
          case "Oct 12":
          case "Oct 13":
          case "Oct 14":
          case "Oct 15":
          case "Oct 16":
          case "Oct 17":
          case "Oct 18":
          case "Oct 19":
          case "Oct 20":
          case "Oct 21":
          case "Oct 22":
              swal("Your horoscope is LIBRA , info");
              break;
          case "Oct 23":
          case "Oct 24":
          case "Oct 25":
          case "Oct 26":
          case "Oct 27":
          case "Oct 28":
          case "Oct 29":
          case "Oct 30":
          case "Oct 31":
          case "Nov 1":
          case "Nov 2":
          case "Nov 3":
          case "Nov 4":
          case "Nov 5":
          case "Nov 6":
          case "Nov 7":
          case "Nov 8":
          case "Nov 9":
          case "Nov 10":
          case "Nov 11":
          case "Nov 12":
          case "Nov 13":
          case "Nov 14":
          case "Nov 15":
          case "Nov 16":
          case "Nov 17":
          case "Nov 18":
          case "Nov 19":
          case "Nov 20":
          case "Nov 21":
              swal("Your Horoscope is SCORPIO , info");
              break;
          case "Nov 22":
          case "Nov 23":
          case "Nov 24":
          case "Nov 25":
          case "Nov 26":
          case "Nov 27":
          case "Nov 28":
          case "Nov 29":
          case "Nov 30":
          case "Dec 1":
          case "Dec 2":
          case "Dec 3":
          case "Dec 4":
          case "Dec 5":
          case "Dec 6":
          case "Dec 7":
          case "Dec 8":
          case "Dec 9":
          case "Dec 10":
          case "Dec 11":
          case "Dec 12":
          case "Dec 13":
          case "Dec 14":
          case "Dec 15":
          case "Dec 16":
          case "Dec 17":
          case "Dec 18":
          case "Dec 19":
          case "Dec 20":
          case "Dec 21":
              swal("Your Horoscope is SAGITTARIUS , info");
              break;
          case "Dec 22":
          case "Dec 23":
          case "Dec 24":
          case "Dec 25":
          case "Dec 26":
          case "Dec 27":
          case "Dec 28":
          case "Dec 29":
          case "Dec 30":
          case "Dec 31":
          case "Jan 1":
          case "Jan 2":
          case "Jan 3":
          case "Jan 4":
          case "Jan 5":
          case "Jan 6":
          case "Jan 7":
          case "Jan 8":
          case "Jan 9":
          case "Jan 10":
          case "Jan 11":
          case "Jan 12":
          case "Jan 13":
          case "Jan 14":
          case "Jan 15":
          case "Jan 16":
          case "Jan 17":
          case "Jan 18":
          case "Jan 19":
          case "Jan 20":
              swal("your Horoscope is CAPRICORN , info");
              break;
      }
  }